version: "2"

services:
  builder:
    build: .
    volumes:
      - /home/davide/dbpedia/:/mnt/dbpedia/
      - /home/davide/dbpedia-spotlight:/mnt/dbpedia-spotlight
    command: ./build_all.sh 2015-10 it


